unstable_features = true
imports_layout = "HorizontalVertical"
imports_granularity = "One"
group_imports = "StdExternalCrate"
error_on_line_overflow = true
error_on_unformatted = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
use_small_heuristics = "Default"
chain_width = 60
max_width = 160
